### ISSUE TITLE
Status Field to API Entity

### ISSUE THREAD

**Issue by kand617** [sudhirtumati/api-collab-server#2]
Each API should have a status field:
Possible status codes:

- STABLE - Will Show on results
- BETA  - Will Show on results
- DEPRECATED  -- Will Show on results (but as deprecated)
- ARCHIVED -- Will be hidden from results

Accordingly the PUT /applications/{applicationId}/apis must allow only updating of the status

**Comment by sudhirtumati** [comment]
Implemented. Changes merged to master with PR #9
